### ISSUE TITLE
Minimum R version requrement?

### ISSUE THREAD

**Issue by ytakemon** [reactome/ReactomeContentService4R#27]
Hello - I'm trying to install your package on R 4.0.2. Ideally, I would like to continue using this version of R; however, I am getting an error saying that this package isn't available (see below). Is there a minimum version of R that is required for this package to install?

```
> BiocManager::install("ReactomeContentService4R")
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://ftp.osuosl.org/pub/cran

Bioconductor version 3.11 (BiocManager 1.30.12), R 4.0.2 (2020-06-22)
Installing package(s) 'ReactomeContentService4R'
Installation paths not writeable, unable to update packages
  path: /gsc/software/linux-x86_64-centos7/R-4.0.2/lib64/R/library
  packages:
    boot, class, cluster, codetools, foreign, KernSmooth, MASS, Matrix, mgcv,
    nlme, nnet, spatial, survival
Old packages: 'DescTools', 'devtools', 'ps', 'RSQLite', 'tidytext', 'usethis',
  'waldo'
Update all/some/none? [a/s/n]: n
Warning message:
package ‘ReactomeContentService4R’ is not available (for R version 4.0.2)
```

**Comment by chilampoon** [comment]
Hi @ytakemon, thank you for your interest in this package!

`ReactomeContentService4R` is still on the Bioconductor develop branch, this is why you got this error. It will be on the official branch in the new Bioconductor release a few weeks later.

You can install it from github using `devtools::install_github("reactome/ReactomeContentService4R")` for now, sorry for the confusion.

**Comment by ytakemon** [comment]
Got it. Thank you for your quick response!
