### ISSUE TITLE
Which database does the `resource` in map2Events() supports?

### ISSUE THREAD

**Issue by kkami1115** [reactome/ReactomeContentService4R#28]
I'm now trying this package but I have a question about this.

The help page lists UniProt and GeneCards as examples of `resource`, but I would like to see a table showing which databases are supported.
Also, with the current error message, I don't know if it is because the database is not supported or because I misspelled the database name.  It would be nice if you could improve it, but I can't think of any way to do that. Sorry.

Anyway, it may depend on the specs of Reactome's API, but please let me know which databases are supported. 

Thanks in advance.

**Comment by chilampoon** [comment]
Hi @kkami1115 yes there's a table for the `resource` (the Name column): https://reactome.org/content/schema/objects/ReferenceDatabase
Database names are case-insensitive.

**Comment by kkami1115** [comment]
Thanks! I think this link should be noted in the Reference Manual or something.

**Comment by chilampoon** [comment]
> Thanks! I think this link should be noted in the Reference Manual or something.

You're right, just found that the link is introduced only here ('non-Reactome resources'): https://bioconductor.org/packages/release/bioc/vignettes/ReactomeContentService4R/inst/doc/ReactomeContentService4R.html#Non-Reactome_id_to_Entities

Thank you and feel free to ask any other questions

**Comment by kkami1115** [comment]
I'll take your word for it and make a new Issue.
