### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by billy-s-lab** [reactome/ReactomeContentService4R#30]
Hi, 
Thank you for the great package.
I am using the latest version of ReactomeContentService4R installed from Bioconductor. It was working as recently as 1-2 weeks ago. However, when I try to load it today, I receive the following error:

Connecting...Error: package or namespace load failed for ‘ReactomeContentService4R’:
 .onAttach failed in attachNamespace() for 'ReactomeContentService4R', details:
  call: curl::curl_fetch_memory(url, handle = handle)
  error: SSL certificate problem: certificate has expired

My R and RStudio versions are up to date. I am on macOS. Session info below.

Any help greatly appreciated. Thank you.

R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_IE.UTF-8/en_IE.UTF-8/en_IE.UTF-8/C/en_IE.UTF-8/en_IE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

**Comment by billy-s-lab** [comment]
I was able to fix this by specifying the following before loading the package:
options(base.address = "http://reactome.org/ContentService")

**Comment by chilampoon** [comment]
hi @billy-s-lab thanks for reporting this issue. I've just updated all dependencies and tried to load `ReactomeContentService4R` on my mac and it worked well. I guess it's a temporary issue from the reactome server side. Happy you solved the problem!
